# Generated by Django 2.0.7 on 2020-07-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='Cartitem',
        ),
    ]
